/**
 * Serverless function to send demo access notifications via Resend
 * Deploy this to Vercel, Netlify, or similar platform
 */

import { Resend } from 'resend';

// Initialize Resend with API key
const resend = new Resend(process.env.RESEND_API_KEY);

interface NotificationRequest {
  userEmail: string;
  domainCategory: string;
  timestamp: string;
  userAgent?: string;
}

export default async function handler(req: any, res: any) {
  // Only allow POST requests
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  try {
    const { userEmail, domainCategory, timestamp, userAgent }: NotificationRequest = req.body;

    // Validate required fields
    if (!userEmail || !domainCategory || !timestamp) {
      return res.status(400).json({ error: 'Missing required fields' });
    }

    // Send notification email
    const { data, error } = await resend.emails.send({
      from: 'MOE Onward Demo <noreply@yourdomain.com>', // Replace with your verified sender
      to: ['lee_kah_how@moe.edu.sg'], // Your notification email
      subject: `Demo Access: ${domainCategory} User`,
      html: `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
          <h2 style="color: #1e40af;">MOE Onward Demo Access Notification</h2>

          <div style="background-color: #f3f4f6; padding: 20px; border-radius: 8px; margin: 20px 0;">
            <h3 style="margin-top: 0; color: #374151;">User Details</h3>
            <p><strong>Email:</strong> ${userEmail}</p>
            <p><strong>Domain Category:</strong> ${domainCategory}</p>
            <p><strong>Access Time:</strong> ${new Date(timestamp).toLocaleString()}</p>
            ${userAgent ? `<p><strong>User Agent:</strong> ${userAgent}</p>` : ''}
          </div>

          <div style="background-color: #dbeafe; padding: 15px; border-radius: 8px; border-left: 4px solid #2563eb;">
            <p style="margin: 0; color: #1e3a8a;">
              A user has accessed the AI chat feature in demo mode.
              This notification helps you track usage and engagement.
            </p>
          </div>

          <hr style="margin: 30px 0; border: none; border-top: 1px solid #e5e7eb;">

          <p style="color: #6b7280; font-size: 14px;">
            This email was automatically generated by the MOE Onward app demo system.
          </p>
        </div>
      `,
      text: `
        MOE Onward Demo Access Notification

        User Details:
        - Email: ${userEmail}
        - Domain Category: ${domainCategory}
        - Access Time: ${new Date(timestamp).toLocaleString()}
        ${userAgent ? `- User Agent: ${userAgent}` : ''}

        A user has accessed the AI chat feature in demo mode.
      `
    });

    if (error) {
      console.error('Resend error:', error);
      return res.status(500).json({ error: 'Failed to send notification' });
    }

    console.log('Notification sent:', { id: data?.id, userEmail, domainCategory });

    return res.status(200).json({
      success: true,
      messageId: data?.id,
      message: 'Notification sent successfully'
    });

  } catch (error) {
    console.error('Server error:', error);
    return res.status(500).json({ error: 'Internal server error' });
  }
}

// For Next.js API routes format
export const config = {
  api: {
    bodyParser: {
      sizeLimit: '1mb',
    },
  },
}